apiVersion: v1
kind: BuildConfig
metadata:
  name: mygovbc-splunk-forwarder
  namespace: gcpe-mygovbc-msp-tools
  selfLink: /oapi/v1/namespaces/gcpe-mygovbc-msp-tools/buildconfigs/mygovbc-splunk-forwarder
  uid: 4eb43737-d912-11e6-89a5-0050568379a2
  resourceVersion: '33902465'
  creationTimestamp: '2017-01-12T21:58:53Z'
  labels:
    app: mygovbc-splunk-forwarder
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  triggers:
    -
      type: Generic
      generic:
        secret: c13779e81f8cc488
    -
      type: GitHub
      github:
        secret: d6263889740e7eab
    -
      type: ImageChange
      imageChange:
        lastTriggeredImageID: 'registry.access.redhat.com/rhscl/nodejs-4-rhel7@sha256:7fdfc09047439b9af110112fa3d289187af6a978addcb9d0e48b018c07728310'
    -
      type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/Splunk-Forwarder'
      ref: master
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:4'
  output:
    to:
      kind: ImageStreamTag
      name: 'mygovbc-splunk-forwarder:latest'
  resources:
  postCommit:
status:
  lastVersion: 6
